# Generated by Django 3.0.3 on 2021-04-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0010_hrmis_v_aw_for_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science_park_rawdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('kpi_number', models.IntegerField()),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
