# Generated by Django 3.0.3 on 2021-04-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0011_science_park_rawdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science_park_rawdata',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='science_park_rawdata',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
