# Generated by Django 3.0.3 on 2021-04-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0012_auto_20210405_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science_park_rawdata',
            name='year',
            field=models.IntegerField(default=2564),
        ),
    ]
