# Generated by Django 3.0.3 on 2021-04-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0013_auto_20210405_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='science_park_rawdata',
            old_name='amount',
            new_name='number',
        ),
    ]
