# Generated by Django 3.0.3 on 2021-06-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importDB', '0014_auto_20210405_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science_park_PITI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('rcv_date', models.DateTimeField(blank=True, null=True)),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('type_group', models.CharField(max_length=15)),
            ],
        ),
    ]
